### ISSUE TITLE
Resolve Imports

### ISSUE THREAD

**Issue by AineeJames** [pherrymason/c3-lsp#31]
When I import the `io` package from the std lib like so:
```c
import std::io;

fn void main() {
    io::<tab>
}
```
Tab does not show any autocompletion. However if I directly do `std::io::<tab>` I do get suggestions.

**Comment by pherrymason** [comment]
Thanks for your report.
I will add there's also a related bug where autocomplete is suggesting things from current scope even if you use full module name.

```
import std::io;

int something;

fn void main() {
    std::io:: // <-- `something` is being suggested too.
}
```

**Comment by pherrymason** [comment]
@AineeJames , I've did some changes and I think it now works as intended.  

![image](https://github.com/user-attachments/assets/400f83dd-702f-42b3-81f1-bd14eac8661f)

Changes are available in `master`, please tell me if there's still scenarios failing.

**Comment by AineeJames** [comment]
Seems to be working for me. Thanks for the fix!
