### ISSUE TITLE
LSP not starting on Windows in VS Code

### ISSUE THREAD

**Issue by Dimension4** [pherrymason/c3-lsp#40]
**Describe the bug**

The VS Code extension can't start the LSP because it appears to be trying to run the linux binary. 

Log:
```
[Error - 10:11:50 PM] C3LSP client: couldn't create connection to server.
Launching server using command ~\.vscode\extensions\tonios2.c3-vscode-0.0.81\c3-lsp-linux failed. Error: spawn ~\.vscode\extensions\tonios2.c3-vscode-0.0.81\c3-lsp-linux ENOENT
```

Setting `c3.lsp.path` in VS Code's settings to point to the windows binary doesn't seem to do anything either

**Desktop (please complete the following information):**
 - OS: Windows 11 (latest)
 - Editor: VS Code (latest)

**Comment by pherrymason** [comment]
Sorry tonios2.c3-vscode is not the extension present in this repository.
It is a derivative from https://github.com/c3lang/editor-plugins

**Comment by Dimension4** [comment]
Oh man I'm sorry, not sure how I ended up in this repo 🥴
