### ISSUE TITLE
Segmentation fault when creating a new function before another function.

### ISSUE THREAD

**Issue by Sampie159** [pherrymason/c3-lsp#55]
**Description**
The server crashes whenever I type the letters `fn` and the next "item" in the file is another function as shown in the first screenshot.

I'm using Emacs 29.4 and lsp-mode.
In the second screenshot is the log message generated.

**To Reproduce**
1. On Emacs with lsp-mode and the c3-lsp setup.
2. Define a function "on top" of another function
3. See error

**Screenshots**
First screenshot:
![image](https://github.com/user-attachments/assets/f59f8804-8933-44bf-9413-642be8db0a12)

Second screenshot:
![image](https://github.com/user-attachments/assets/da5c0762-3981-4b9f-9880-149c398e8554)

**Desktop:**
 - OS: Arch Linux
 - Editor: Emacs
 - Version: 29.4

**Comment by pherrymason** [comment]
What version of LSP are you using?

**Comment by Sampie159** [comment]
I'm building directly from source every time I try to use it, so the most current one.

**Comment by pherrymason** [comment]
I'm guessing the source code is in an invalid state and the parser cannot give a reliable result, making the LSP crash because an edge case.

Will take a look at the details.

**Comment by pherrymason** [comment]
Added some control checks to avoid this crash.
