### ISSUE TITLE
Toggle comment is not working for C3 in Sublime text

### ISSUE THREAD

**Issue by kcvinker** [pherrymason/c3-lsp#58]
Hi,
Toggle comment is not working for C3 in Sublime text. My short cut key is `Ctrl + /`. This key is working for all other language but C3.

**Comment by pherrymason** [comment]
Not sure if this is solvable with the LSP.

VSCode have for example language configuration to customize this: https://code.visualstudio.com/api/language-extensions/language-configuration-guide

Maybe Sublimetext needs something similar?

**Comment by kcvinker** [comment]
I am not sure about that but one thing is sure, all other languages have no problem with `Ctrl + /` shortcut.

**Comment by tomaskallup** [comment]
This is definitely not a job of LSP, but rather editors support for the language syntax. Your issue should probably be directed to https://github.com/c3lang/editor-plugins/ if that's the one you use.

**Comment by pherrymason** [comment]
After reading the specification I cannot find any feature related to this.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/

Feel free to correct me if I missed anything.
