### ISSUE TITLE
Function signature is unaware of slices?

### ISSUE THREAD

**Issue by joshring** [pherrymason/c3-lsp#63]
**Describe the bug**
Slice inner type is correctly reported, but the slice itself seems to be omitted in the  function signature on hover

**To Reproduce**
Create function which uses a slice, eg
```c
fn void main(String[] args) 
{
    return;
}
```

**Expected behavior**
Expect the signature to mention the type is a slice of the type reported

**Screenshots**
![image](https://github.com/user-attachments/assets/3ea8ff6e-e51f-4182-a84d-996a477676c9)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 
 - Editor Visual Studio Code
 - Version: 
 > 1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
x64

**Additional context**

**Comment by pherrymason** [comment]
Good catch.
Happens everywhere, not only on function signatures.

**Comment by joshring** [comment]
I noticed that this is fixed in many places, but the function argument is still not being spotted as a slice:

![image](https://github.com/user-attachments/assets/1cb23082-39ff-4403-a423-cd17bdc53d67)
