### ISSUE TITLE
add the exec permission and use tar.gz format for linux release

### ISSUE THREAD

**Issue by id3nom** [pherrymason/c3-lsp#65]
Currently the linux binary release file are zip and the c3lsp binary don't have the execute permission,
zip is not always available on linux platform, which force the installation of another program the deflate the archive,
Also the execute permission is required to be able to execute a binary. 

It would be better to add the read+execute permission '`chmod 0555 c3lsp`' on the c3lsp binary and  create a 'tar.gz' archive with a command like '`tar -czf c3lsp-linux-amd64.tar.gz ./release-dir-name`', this would greatly improve the linux deployment.

**Comment by pherrymason** [comment]
Added the suggested changes to the `pack-release` goal of the make file.
