### ISSUE TITLE
VSCode LSP executable not runnable on Mac OS

### ISSUE THREAD

**Issue by wowselim** [pherrymason/c3-lsp#75]
**Describe the bug**
The mac os executable that is installed by the vscode extension is not runnable by default.

**To Reproduce**
1. Install the vscode extension
2. Open a C3 file
3. See that it fails to start the LSP process

**Expected behavior**
Executable flag should be set on mac os binary like it is for the linux binary.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Editor: Visual Studio Code
 - Version: 1.92.2

**Additional context**
Found this issue for the linux executable facing the same issue:

https://github.com/pherrymason/c3-lsp/issues/65

On my machine running `chmod +x c3-lsp-darwin-arm64` fixed the problem and the LSP worked afterwards.

**Comment by pherrymason** [comment]
Fixed
