### ISSUE TITLE
BSD Make fails to build due to bad indentation.

### ISSUE THREAD

**Issue by julia-gh** [pherrymason/c3-lsp#78]
**Describe the bug**
BSD make fails when running `make build` due to bad indentation.

**To Reproduce**
1. Clone the repo with `git clone https://github.com/pherrymason/c3-lsp.git`.
2. cd into the repo with `cd c3-lsp`.
3. Run `make build`.
 
**Expected behavior**
I expected BSD make to properly build the project.

**Screenshots**

The error:
![make](https://github.com/user-attachments/assets/28e1e37f-5d28-4e28-9560-177250ab47a6)

One of the bad indentations (The error message contains all the line numbers of the occurances):
![bad-indent](https://github.com/user-attachments/assets/34b73043-eb9a-4cc3-b3c9-cc9d00a6079f)

**Desktop (please complete the following information):**
 - OS: FreeBSD 14.1-RELEASE on AMD64
 - Editor Helix
 - Version 24.3

**Additional context**
I would have liked to create a PR to save you all some time, but I am not comfortable enough with `git` and GitHub to do so yet.

Considering this builds fine with GNU make, I recommend to either fix the indentation to make it work with BSD make, or add a list of "prerequisites" and explicitly specify GNU make and other required programs like `go` to avoid future confusion.

**EDIT:**
Only just now noticed the "Version" field was meant for your editor, so I have edited it accordingly.

**Comment by pherrymason** [comment]
Thank you for your feedback.
I'm not an expert in makefile nor in their different flavors (I was not aware of that). In my system it works flawlessly.

I've moved the logic of those targets to a separate .sh file so I think this fixes the issue.

**Comment by julia-gh** [comment]
> Thank you for your feedback. I'm not an expert in makefile nor in their different flavors (I was not aware of that). In my system it works flawlessly.

You're very welcome! The reason why this works on your system without issue is likely because GNU make is the standard on.....most if not all systems aside from the BSDs, plan9, etc, and is often simply installed as "make". FreeBSD installs its own Make as "make" and installs GNU Make as "gmake".

> I've moved the logic of those targets to a separate .sh file so I think this fixes the issue. Please let me know if there are still other issues.

Alright! I tried building it and so far I only noticed two minor problems, one of which is because of FreeBSD itself:
1. In your Makefile, when you execute the shell scripts, some of the paths are not made relative. While it is not mandatory, it is more reliable and good practice in general to make them relative.
2. On FreeBSD, `bash` is located at `/usr/local/bin/bash`, not `/bin/bash`, and while the shebang of `/bin/bash` will not outright fail the build, the fact it cannot find any interpreter for the script will fail the build. 
What would fix this with minimal changes to your code would be to prepend `bash` to all of your calls to your shell scripts in your Makefile, so `bin/build.sh` would turn into `bash ./bin/buikd.sh`.

After making these changes to the Makefile manually, I was able to build it under FreeBSD 14.1-RELEASE without issue.

**NOTE**:
I wasn't sure if I should've created a seperate issue as this one is now closed, or instead revive this one, but I chose to revive this one as it still results in failed builds like the previous issue. Please do let me know what the better course of action is for future issues.

**Comment by pherrymason** [comment]
Thanks for this extended feedback, I prefer to keep it in this very same issue, it helps keep track of history of changes if is not have been fixed yet.

**Comment by pherrymason** [comment]
> On FreeBSD, bash is located at /usr/local/bin/bash, not /bin/bash, and while the shebang of /bin/bash will not outright fail the build, the fact it cannot find any interpreter for the script will fail the build.
What would fix this with minimal changes to your code would be to prepend bash to all of your calls to your shell scripts in your Makefile, so bin/build.sh would turn into bash ./bin/buikd.sh.

Should I then remove `#!/bin/bash` then if i call the script with `bash bin/xxx.sh`?

**Comment by julia-gh** [comment]
> Should I then remove `#!/bin/bash` then if i call the script with `bash bin/xxx.sh`?

Yes that's what I would do considering you're forcing the script to run through `bash`. If it causes any problems, you can always add your shebangs back.

Oh- and don't forget to make all the paths relative (`bash bin/xxx.sh` -> `bash ./bin/xxx.sh`).

**Comment by pherrymason** [comment]
I applied all changes you suggested.

**Comment by julia-gh** [comment]
> I applied all changes you suggested.

Thank you! I was able to build it without any problems this time. If you'd like, you can close this issue, or I could close it for you if you prefer that.

**Comment by pherrymason** [comment]
Thank you for your help!
