### ISSUE TITLE
Diagnostic error persisting after resolving error

### ISSUE THREAD

**Issue by anthony-63** [pherrymason/c3-lsp#83]
**Describe the bug**
When the diagnostics produce an error, and then the error is fixed, the error still persists.

**To Reproduce**
```c3
module probe;
import std::io;

fn void main() {
	test // error expected here and it does produce "Expected ';'"
}
```
```c3
module probe;
import std::io;

fn void main() {
	// error still persisting "Expected ';'"
}
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor VSCode Insiders
 - Version: 1.95

**Comment by pherrymason** [comment]
I suspect this is related to the different way Windows represents path to files.
Will need to setup my windows machine to debug this.
Sorry for the time it is taking

**Comment by pherrymason** [comment]
Could you try this https://github.com/pherrymason/c3-lsp/actions/runs/12147202612/artifacts/2269628742 and see if it fixes this issue? (It's a zip with linux, mac and windows builds)
